import {
  faruzan,
  ganyu,
  fischl,
  gorou,
  hutao,
  raidenShogun,
  klee,
  ayaka,
  amber,
  aether,
  albedo,
  alhaitham,
  arataki,
  ayato,
  baizhu,
  beidou,
  bennett,
  barbara,
  candace,
  chongyun,
  collei,
  cyno,
  dehya,
  diluc,
  diona,
  dori,
  eula,
  jean,
  kaeya,
  kaveh,
  kazuha,
  keqing,
  kirara,
  kokomi,
  kujouSara,
  kukiShinobu,
  layla,
  lisa,
  lumine,
  mika,
  mona,
  nahida,
  nilou,
  ningguang,
  noelle,
  paimon,
  qiqi,
  razor,
  rosaria,
  sayu,
  shenhe,
  shikanoinHeizou,
  sucrose,
  tartaglia,
  thoma,
  tighnari,
  venti,
  wanderer,
  xiangling,
  xiao,
  xingqiu,
  xinyan,
  yaeMiko,
  yanfei,
  yaoyao,
  yelan,
  yoimiya,
  yunjin,
  zhongli,
} from "./character";

export const genshinCharacter = [
  { name: "Raiden Shogun", image: raidenShogun },
  { name: "Klee", image: klee },
  { name: "Nahida", image: nahida },
  { name: "Yae Miko", image: yaeMiko },
  { name: "Yao Yao", image: yaoyao },
  { name: "Kirara", image: kirara },
  { name: "Shenhe", image: shenhe },
  { name: "Kamisato Ayaka", image: ayaka },
  { name: "Nilou", image: nilou },
  { name: "Ganyu", image: ganyu },
  { name: "Amber", image: amber },
  { name: "Faruzan", image: faruzan },
  { name: "Barbara", image: barbara },
  { name: "Hu Tao", image: hutao },
  { name: "Diona", image: diona },
  { name: "Eula", image: eula },
  { name: "Collei", image: collei },
  { name: "Sangonomiya Kokomi", image: kokomi },
  { name: "Ningguang", image: ningguang },
  { name: "Jean", image: jean },
  { name: "Lisa", image: lisa },
  { name: "Layla", image: layla },
  { name: "Yoimiya", image: yoimiya },
  { name: "Yelan", image: yelan },
  { name: "Yanfei", image: yanfei },
  { name: "Yun Jin", image: yunjin },
  { name: "QiQi", image: qiqi },
  { name: "Paimon", image: paimon },
  { name: "Keqing", image: keqing },
  { name: "Xiangling", image: xiangling },
  { name: "Xinyan", image: xinyan },
  { name: "Mona", image: mona },
  { name: "Kuki Shinobu", image: kukiShinobu },
  { name: "Lumine", image: lumine },
  { name: "Noelle", image: noelle },
  { name: "Fischl", image: fischl },
  { name: "Beidou", image: beidou },
  { name: "Sucrose", image: sucrose },
  { name: "Candace", image: candace },
  { name: "Dehya", image: dehya },
  { name: "Kujou Sara", image: kujouSara },
  { name: "Dori", image: dori },
  { name: "Sayu", image: sayu },
  { name: "Rosaria", image: rosaria },
  { name: "Zhongli", image: zhongli },
  { name: "Diluc", image: diluc },
  { name: "Xiao", image: xiao },
  { name: "Gorou", image: gorou },
  { name: "Aether", image: aether },
  { name: "Albedo", image: albedo },
  { name: "Arataki Itto", image: arataki },
  { name: "Alhaitham", image: alhaitham },
  { name: "Kamisato Ayato", image: ayato },
  { name: "Kaveh", image: kaveh },
  { name: "Kaedehara Kazuha", image: kazuha },
  { name: "Baizhu", image: baizhu },
  { name: "Tartaglia", image: tartaglia },
  { name: "Thoma", image: thoma },
  { name: "Tighnari", image: tighnari },
  { name: "Venti", image: venti },
  { name: "Cyno", image: cyno },
  { name: "Bennett", image: bennett },
  { name: "Chongyun", image: chongyun },
  { name: "Kaeya", image: kaeya },
  { name: "Mika", image: mika },
  { name: "Razor", image: razor },
  { name: "Shikanoin Heizou", image: shikanoinHeizou },
  { name: "Wanderer", image: wanderer },
  { name: "Xingqiu", image: xingqiu },
].map((genshinCharacter) => ({ ...genshinCharacter, isClicked: false }));
